---
title: "Drosophila slices"
author: "Yang， Tao & Jie"
date: "2023-06-19"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
### Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r packages}
library(limma)
library(Seurat)
library(readr)
library(edgeR)
library(AnnotationHub)
library(tidyverse)
library(magrittr)
library(pander)
library(ggrepel)
library(scales)
library(plyr)
library(purrr)
library(scatterplot3d)
library(rgl)
library(SingleCellExperiment)
library(Matrix.utils)
library(reshape2)
library(ggalt)
library(ggtext)
library(BayesSpace)
library(MuSiC)
library(scater)
library(ggplot2)
library(ggpubr)
library(scater)


theme_set(theme_bw())
panderOptions("big.mark", ",")
panderOptions("table.split.table", Inf)
panderOptions("table.style", "rmarkdown")
if (interactive()) setwd(here::here("analysis"))
```
### Seurat object construction
```{r}
E14h_counts <- read.table(here::here("reference","stereoseq data","drosophila","X.csv"), sep = ",")
E14h_genename <- read_csv(here::here("reference","stereoseq data","drosophila","var.csv"))
colnames(E14h_counts) <- E14h_genename$geneID

E14h_metadata <- read.csv(here::here("reference","stereoseq data","drosophila","obs.csv"))
rownames(E14h_counts) <- E14h_metadata$X


E14h_counts.matrix <- E14h_counts %>%
  as.matrix() %>%
  t()

E14h_st <- CreateSeuratObject(counts = E14h_counts.matrix, project = "E14h_st")

E14h_st@meta.data$slice_ID <- E14h_metadata$slice_ID
E14h_st@meta.data$raw_x <- E14h_metadata$raw_x
E14h_st@meta.data$raw_y <- E14h_metadata$raw_y
E14h_st@meta.data$new_x <- E14h_metadata$new_x
E14h_st@meta.data$new_y <- E14h_metadata$new_y
E14h_st@meta.data$new_z <- E14h_metadata$new_z
E14h_st@meta.data$annotation <- E14h_metadata$annotation
write_rds(E14h_st, here::here("output","E14h","E14h_st_seurat.rds"), compress = "gz")

```

```{r}
slice_subset = subset(E14h_st, subset = slice_ID == "E14-16h_a_S04" | slice_ID == "E14-16h_a_S05" | slice_ID == "E14-16h_a_S06")

color_df <- data.frame(unique(slice_subset$annotation))
colnames(color_df)[1] <- "annotation"
color_df$color <- c("#FFF799","#2ED9FF",
                              "#683b79",
                              "#009200",
                              "#6e9BC5",
                              "#F091A0",
                              "#FEAF16",
      "#ff66ff","#AEF359","#C0C0C0")

x <- slice_subset@meta.data %>%
  left_join(color_df)

slice_subset@meta.data$color <- x$color


slice_4 <- subset(slice_subset, subset = slice_ID == "E14-16h_a_S04")
slice_5 <- subset(slice_subset, subset = slice_ID == "E14-16h_a_S05")
slice_6 <- subset(slice_subset, subset = slice_ID == "E14-16h_a_S06")


ggplot(slice_4@meta.data %>% as.data.frame(),aes(x=new_x, y=new_y, color=color)) +
  geom_point(size=0.5) +
  theme_classic() +
  xlim(-25, 25) +
  ylim(-25, 25) +
    coord_fixed(ratio = 1, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  scale_color_manual(values = levels(slice_4@meta.data$color %>% as.factor())) +
  theme_classic() +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none") 

  # labs(title = "10 hpf-slice1") +
  # theme(plot.title = element_markdown(box.color = "black",
  #                                     linewidth = 0.5,
  #                                     r = unit(0, "mm"), linetype = 1,
  #                                     padding = unit(3, "mm"),
  #                                     hjust = 0.5, 
  #                                     size = 15,
  #                                     face='bold')) +


write_rds(slice_subset, here::here("output","E14h","slice_subset.rds"), compress = "gz")
```

```{r}
slice_subset <- readRDS(here::here("output","E14h","slice_subset.rds"))

slice_sce <- SingleCellExperiment(assays = list(counts = slice_subset@assays$RNA@counts), 
                           colData = slice_subset@meta.data)
slice_bulk <- colSums(t(slice_subset@assays$RNA@data)) %>% as.data.frame() 

groups <- colData(slice_sce)[, c("slice_ID")]
slice_bulk <- aggregate.Matrix(t(counts(slice_sce)), 
                       groupings = groups, fun = "sum") %>% 
  as.data.frame() %>% t()


slice_4_ST_sum <- slice_bulk[,1, drop = FALSE]

slice_4_ST_sum_high_expressed <- slice_4_ST_sum %>%
  as.data.frame() %>%
  set_colnames("Counts") %>%
  dplyr::filter(rownames(.) %in% rownames(slice_bulk)) %>%
  dplyr::filter(.$Counts > 30)


slice_bulk_high_expressed_reorder <- slice_bulk[match(rownames(slice_4_ST_sum_high_expressed), rownames(slice_bulk)),,drop = FALSE] %>%
  as.data.frame()
```

### Get stable genes 
```{r}
gene_filter <- slice_bulk_high_expressed_reorder[,2,drop = FALSE]/slice_4_ST_sum_high_expressed 
colnames(gene_filter) <- "factor"

gene_filter_filtered <- gene_filter %>%
     .[is.finite(rowSums(.)),, drop = FALSE] 
gene_filter_filtered$differ <- abs(gene_filter_filtered$factor - (mean(gene_filter_filtered$factor)+median(gene_filter_filtered$factor))/2)

stable_genes <- gene_filter_filtered %>%
  .[order(.$differ),] %>%
   top_n(.,-2000)
```


### spatial clustering and deconvolution
```{r}
slice_4 <- subset(slice_subset, subset = slice_ID == "E14-16h_a_S04")
metadata <-  slice_4@meta.data
metadata$col <-  metadata$new_x %>% as.numeric() %>% as.integer()
metadata$row <-  metadata$new_y %>% as.numeric() %>% as.integer()

sce <- SingleCellExperiment(assays = list(counts = slice_4@assays$RNA@counts, logcounts = slice_4@assays$RNA@data),
                            colData=metadata)


sce_filtered <- sce[rownames(stable_genes),]
sce_filtered <- spatialPreprocess(sce_filtered, platform="ST", 
                              n.PCs=4,n.HVGs = 2000, log.normalize=TRUE)


p <- qTune(sce_filtered, qs=seq(2, 10), platform="ST")
qPlot(p)

set.seed(149)
cluster <- spatialCluster(p, q=5, platform="ST", d=7,
                           init.method="kmeans", model="t", gamma=2,
                           nrep=10000, burn.in=100,
                           save.chain=TRUE)

clusterPlot(cluster, color="black") +
  theme_bw() +
  xlab("Column") +
  ylab("Row") 



slice_4$spatial_cluster <- cluster$spatial.cluster

prop.table(table(slice_4$spatial_cluster))
Idents(slice_4) <- slice_4$spatial_cluster
```

### Deconvolution
```{r}

bulk.est <- Biobase::ExpressionSet(assayData = slice_bulk %>% as.matrix())


sc.eset <- ExpressionSet(assayData = as.matrix(GetAssayData(slice_4[rownames(stable_genes),])), phenoData = new("AnnotatedDataFrame", slice_4@meta.data))

Est.pro = music_prop(bulk.eset = bulk.est, sc.eset = sc.eset,  clusters = "spatial_cluster")
proportion <- Est.pro$Est.prop.weighted
proportion_reorder <- proportion[, c("1","2","3","4","5")]

```


### variable factor calculation
```{r}
cluster.averages <- AverageExpression(slice_4) %>%
  as.data.frame() %>%
  as.matrix()

cluster.averages_filtered <- cluster.averages %>%
  as.data.frame() %>%
  rownames_to_column() %>% 
  dplyr::filter(.$rowname %in% rownames(slice_bulk)) %>%
  column_to_rownames(var= "rowname")  %>%
  as.matrix() %>%
  .[,c("RNA.1","RNA.2","RNA.3","RNA.4","RNA.5")]


abundance <- proportion_reorder %>%
  .[2,,drop=FALSE] %>% 
  as.data.frame() %>% 
  as.matrix()

# adjusted_matrix <- cluster.averages_filtered_reorder %*% abundance 

bulk_reorder <- slice_bulk[match(rownames(cluster.averages_filtered), rownames(slice_bulk)),2,drop=FALSE] %>%
  as.data.frame() 

# lib_size_ratio <- sum(S10_2_counts_bulk.set)/sum(adjusted_matrix)

# variable_factor <- S10_2_counts_bulk.set_reorder/(adjusted_matrix * lib_size_ratio) 
variable_factor <- bulk_reorder/(cluster.averages_filtered %*% (abundance %>% t())) 

variable_factor_filtered <- variable_factor %>% 
  .[is.finite(rowSums(.)),, drop = FALSE] %>%
    as.data.frame()

variable_factor_filtered_2 <- rep(variable_factor_filtered,5) %>%
  as.data.frame() %>%
  set_colnames(c("1","2","3","4","5"))
rownames(variable_factor_filtered_2) <- rownames(variable_factor_filtered)


adjusted_matrix <- ((cluster.averages_filtered[rownames(variable_factor_filtered_2),] * variable_factor_filtered_2)) 

```


### Estimate expression of each spot
```{r}
#### Nearest 8 spots
ST <- colSums(t((slice_4@assays$RNA@data))) %>%
    as.data.frame() %>%
    rownames_to_column() %>%
    dplyr::select(Gene=rowname, Counts = '.')



output_final <- data.frame(matrix(ncol = 0, nrow = length(rownames(variable_factor_filtered))))
rownames(output_final) <- rownames(variable_factor_filtered)
for (i in 1:5000) {
  set.seed(i)
  slice_4.random.obj <- slice_4[, sample(colnames(slice_4), size = 1, replace=F)]
  spot <- slice_4.random.obj@meta.data[,c("new_x","new_y")] %>% as.data.frame()
  df <- slice_4@meta.data[,c("new_x","new_y")] %>% as.data.frame()
  df$distance = sqrt((df$new_x - spot$new_x)^2 + (df$new_y - spot$new_y)^2)
  df <- df[order(df$distance),][1:9,] 
  slice_4.random.neighbor <-  slice_4[,rownames(df)]
  
  output_region <- data.frame(matrix(ncol = 0, nrow = length(rownames(variable_factor_filtered))))
  rownames(output_region) <- rownames(variable_factor_filtered)
  for (k in as.numeric(levels(as.factor(slice_4.random.neighbor$spatial_cluster)))){
    cluster <- subset(slice_4.random.neighbor, subset = spatial_cluster == k)
  
    RST <- colSums(t((cluster@assays$RNA@counts))) %>%
      as.data.frame() %>%
      rownames_to_column() %>%
      dplyr::select(Gene=rowname, Counts = '.')
    
    K <- RST$Counts/ST$Counts %>%
      as.data.frame()
    rownames(K) <- ST$Gene
    
    K_filtered <- K %>%
      rownames_to_column() %>%
      dplyr::select(Gene=rowname, factor = '.') %>%
      dplyr::filter(.$Gene %in% rownames(variable_factor_filtered)) %>%
      column_to_rownames(var= "Gene")  %>%
      as.matrix()
    
    region_bulk <- (adjusted_matrix[,k] %>% as.data.frame()) * K_filtered
    each_spot <- data.frame(region_bulk/length(cluster$orig.ident))
    output <- cbind(each_spot, rep(each_spot[1],  length(cluster$orig.ident)))
    output <- output[1:(length(output)-1)]
    colnames(output) <- rownames(cluster@meta.data)
    output_region <- output_region %>%
      cbind(output)
    }
  output_final <- output_final %>% 
    cbind(output_region)
}


cell_list <- as.list(rownames(slice_4@meta.data))

spot_average_counts_final <- data.frame(matrix(ncol = 0, nrow = length(rownames(variable_factor_filtered))))
rownames(spot_average_counts_final) <- rownames(variable_factor_filtered)
spot_rep_times <- data.frame()

for ( i in 1:length(cell_list)) {
  spot <- colnames(output_final) == cell_list[i] 
  spot_counts <- output_final[, spot, drop = FALSE]
  spot_rep_times <- spot_rep_times %>%
    rbind(length(colnames(spot_counts)))
  spot_average_counts <-  data.frame(rowSums(spot_counts))/length(spot_counts)
  colnames(spot_average_counts) <- cell_list[i] 
  spot_average_counts_final <- spot_average_counts_final %>%
    cbind(spot_average_counts)
}

```

```{r}
slice_4_adjusted <- CreateSeuratObject(spot_average_counts_final,assay = "RNA",meta.data = metadata)

slice_4_adjusted@images$image <- slice_4@images$image

metadata <-  slice_4_adjusted@meta.data
metadata$col <-  slice_4_adjusted@meta.data$col
metadata$row <-  slice_4_adjusted@meta.data$row

saveRDS(slice_4_adjusted, here::here("output","E14h","slice_4_adjusted.rds"))


sce_S4 <- SingleCellExperiment(assays = list(counts = slice_4_adjusted@assays$RNA@counts, logcounts = slice_4_adjusted@assays$RNA@data),
                            colData= metadata)

sce_S4 <- spatialPreprocess(sce_S4, platform="ST", 
                              n.PCs=4,n.HVGs = 2000, log.normalize=FALSE,skip.PCA=TRUE)


featurePlot(
  sce_S4,
  "CG6337",
  assay.type = "logcounts",
  diverging = FALSE,
  low = NULL,
  high = "darkblue",
  mid = NULL,
  color = NULL,
  platform = NULL,
  is.enhanced = NULL,
)

saveRDS(slice_5, here::here("output","E14h","slice_5.rds"))

slice_5_metadata <-  slice_5@meta.data
slice_5_metadata$col <-  slice_5_metadata$new_x %>% as.numeric() %>% as.integer()
slice_5_metadata$row <-  slice_5_metadata$new_y %>% as.numeric() %>% as.integer()


sce_S5 <- SingleCellExperiment(assays = list(counts = slice_5@assays$RNA@counts, logcounts = slice_5@assays$RNA@data),
                            colData=slice_5_metadata)

sce_S5 <- spatialPreprocess(sce_S5, platform="ST", 
                              n.PCs=4,n.HVGs = 2000, log.normalize=FALSE,skip.PCA=TRUE)
markers <- FindAllMarkers(slice_5)
featurePlot(
  sce_S5,
  "CG6337",
  assay.type = "logcounts",
  diverging = FALSE,
  low = NULL,
  high = "darkblue",
  mid = NULL,
  color = NULL,
  platform = NULL,
  is.enhanced = NULL,
)

```

#### Performance comparison
```{r}
# nCounts
gene_counts <- colSums(slice_4_adjusted@assays$RNA@data %>% as.data.frame()) %>% as.data.frame() %>%
  set_colnames("Number")
gene_counts$group <- "Adjusted_S04"

gene_counts_origin <- colSums(slice_5@assays$RNA@data %>% as.data.frame()) %>% as.data.frame() %>%
  set_colnames("Number")
gene_counts_origin$group <- "S05"

gene_counts_merge <- rbind(gene_counts_origin, gene_counts)

ggboxplot(data = gene_counts_merge, x= "group",y="Number",xlab = FALSE, ylab = "nCounts",
          color = "group",
          #legend = "right"
          ) 
ggplot(gene_counts_merge, aes(x=factor(group), y=Number, color=group)) + 
  labs(title="Plot of nCount", y = "nCounts")+
  geom_boxplot(width=0.4,outlier.shape = NA) +
  theme_classic() +
  theme(legend.position = "none") +
  scale_x_discrete(limits=c("S05", "Adjusted_S04")) +
  scale_color_manual(values=c("#C77CFF","#56B4E9"))


# nFeatures
gene_number <- nexprs(slice_4_adjusted@assays$RNA@data) %>% as.data.frame() %>%
  set_colnames("Number")
gene_number$group <- "Adjusted_S04"
gene_number_origin <- nexprs(slice_5@assays$RNA@counts) %>% as.data.frame() %>%
  set_colnames("Number")
gene_number_origin$group <- "S05"

gene_number_merge <- rbind(gene_number_origin, gene_number)


ggboxplot(data = gene_number_merge, x= "group",y="Number",xlab = FALSE, ylab = "nFeatures",
          color = "group",
          #legend = "right"
          ) + theme(legend.position = "none")

ggplot(gene_number_merge, aes(x=factor(group), y=Number, color=group)) + 
  labs(title="Plot of nCount", y = "nFeatures")+
  geom_boxplot(width=0.4,outlier.shape = NA) +
  theme_classic() +
  theme(legend.position = "none") +
  scale_x_discrete(limits=c("S05", "Adjusted_S04")) +
  scale_color_manual(values=c("#C77CFF","#56B4E9"))




```

#### Performance comparison
```{r}
# nCounts
gene_counts <- colSums(slice_4_adjusted@assays$RNA@data %>% as.data.frame()) %>% as.data.frame() %>%
  set_colnames("Number")
gene_counts$group <- "Adjusted_S04"

gene_counts_origin <- colSums(slice_4@assays$RNA@data %>% as.data.frame()) %>% as.data.frame() %>%
  set_colnames("Number")
gene_counts_origin$group <- "S04"

gene_counts_merge <- rbind(gene_counts_origin, gene_counts)

ggboxplot(data = gene_counts_merge, x= "group",y="Number",xlab = FALSE, ylab = "nCounts",
          color = "group",
          #legend = "right"
          ) 
ggplot(gene_counts_merge, aes(x=factor(group), y=Number, color=group)) + 
  labs(title="Plot of nCount", y = "nCounts")+
  geom_boxplot(width=0.4,outlier.shape = NA) +
  theme_classic() +
  theme(legend.position = "none") +
  scale_x_discrete(limits=c("S04", "Adjusted_S04")) +
  scale_color_manual(values=c("#C77CFF","#56B4E9"))


# nFeatures
gene_number <- nexprs(slice_4_adjusted@assays$RNA@data) %>% as.data.frame() %>%
  set_colnames("Number")
gene_number$group <- "Adjusted_S04"
gene_number_origin <- nexprs(slice_4@assays$RNA@counts) %>% as.data.frame() %>%
  set_colnames("Number")
gene_number_origin$group <- "S04"

gene_number_merge <- rbind(gene_number_origin, gene_number)


ggboxplot(data = gene_number_merge, x= "group",y="Number",xlab = FALSE, ylab = "nFeatures",
          color = "group",
          #legend = "right"
          ) + theme(legend.position = "none")

ggplot(gene_number_merge, aes(x=factor(group), y=Number, color=group)) + 
  labs(title="Plot of nCount", y = "nFeatures")+
  geom_boxplot(width=0.4,outlier.shape = NA) +
  theme_classic() +
  theme(legend.position = "none") +
  scale_x_discrete(limits=c("S04", "Adjusted_S04")) +
  scale_color_manual(values=c("#C77CFF","#56B4E9"))




```

### Expression correlation of Marker genes
```{r}
Idents(slice_5) <- slice_5$annotation
Markers <- FindAllMarkers(slice_5,logfc.threshold = 0.3) 

top5 <- Markers %>%
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC) 


S05_df <- data.frame(row.names = rownames(slice_5)[(rownames(slice_5) %in% top5$gene)])
for (i in unique(slice_5$annotation) ){
  subset <- subset(slice_5, subset = annotation == i)
  subset_features <- subset[top5$gene,]@assays[["RNA"]]@data %>%
    rowMeans() %>%
    as.data.frame()
  colnames(subset_features) <- print(i)
  S05_df <- S05_df %>%
    cbind(subset_features)
}


Adjusted_S04_df <- data.frame(row.names = rownames(slice_4_adjusted)[(rownames(slice_4_adjusted) %in% top5$gene)])
for (i in unique(slice_4_adjusted$annotation) ){
  subset <- subset(slice_4_adjusted, subset = annotation == i)
  subset_features <- subset[top5$gene,]@assays[["RNA"]]@data %>%
    rowMeans() %>%
    as.data.frame()
  colnames(subset_features) <- print(i)
  Adjusted_S04_df <- Adjusted_S04_df %>%
    cbind(subset_features)
}


order <- c("CNS","epidermis","muscle","trachea","fat body","amnioserosa","midgut","salivary gland")
x <- S05_df[rownames(S05_df),order]
y <- Adjusted_S04_df[rownames(S05_df),order]

colnames(x) <- paste0(colnames(x) , "_S05")
colnames(y) <- paste0(colnames(y) , "_S04")

output <- data.frame(row.names = colnames(x))
p.val <- data.frame(row.names = colnames(x))
for (j in 1:ncol(x)) {
  for (i in 1:ncol(y)) {
    a <- cor.test(x[,j], y[,i], method = "pearson") 
    output[j,i] <- a$estimate
    p.val[j,i] <- a$p.value
    colnames(output)[i] <- colnames(y)[i]
    colnames(p.val)[i] <- colnames(y)[i]
  }
}

pheatmap::pheatmap(output,
                   cluster_rows=FALSE,
                   cluster_cols=FALSE,
                   cellwidth = 25,
                   cellheight = 25,
               #    display_numbers = p.val
                 )
```


### Plot signal intensity
```{r}
ISH <- read_csv(here::here("slice images","E14","intensity","CG6337_ISH.csv"))
ISH$x <- ISH$`Distance_(pixels)`/max(ISH$`Distance_(pixels)`)
ISH$Group <- c("ISH")
ISH$z <- ISH$Gray_Value %>% scale()
ISH <- ISH %>% as.data.frame() %>% dplyr::select(-`Distance_(pixels)`)


Adjusted_S04 <- read_csv(here::here("slice images","E14","intensity","CG6337_adjusted_S04.csv"))
Adjusted_S04$x <- Adjusted_S04$`Distance_(inches)`/max(Adjusted_S04$`Distance_(inches)`)
Adjusted_S04$Group <- c("Adjusted_S04")
Adjusted_S04$z <- Adjusted_S04$Gray_Value %>% scale()
Adjusted_S04 <- Adjusted_S04 %>% as.data.frame() %>% dplyr::select(-`Distance_(inches)`)

S05 <- read_csv(here::here("slice images","E14","intensity","CG6337_S05.csv"))
S05$x <- S05$`Distance_(inches)`/max(S05$`Distance_(inches)`)
S05$Group <- c("S05")
S05$z <- S05$Gray_Value %>% scale()
S05 <- S05 %>% as.data.frame() %>% dplyr::select(-`Distance_(inches)`)

Merged <- ISH %>%
  rbind(Adjusted_S04) %>%
  rbind(S05) 

ggplot(data = Merged, aes(x, y = z, col=Group)) +
  geom_line(linetype="solid", size=0.5) +
  labs( x="Distance_AP", y="Scaled intensity")  +
  scale_x_continuous(breaks=seq(0,1,0.2), labels=seq(0,1,0.2)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.position = "none") +
  theme(plot.title = element_markdown(box.color = "black",
                                      linewidth = 0.5,
                                      r = unit(0, "mm"), linetype = 1,
                                      padding = unit(3, "mm"),
                                      hjust = 0.5,
                                      size = 12,
                                      face='bold')) +
  coord_fixed(ratio = 0.1, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  scale_color_manual(values = c("#C77CFF",
                              "#3366ff",
                              "#F9A603"))

```
