---
title: "6. 3D projection to live image"
author: "Yang"
date: "2023-06-01"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
### Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(XML)
library(methods)
library(xml2)
library(tibble)
library(rvest)
library(dplyr)
library(rgl)
library(scatterplot3d)
library(pracma)
library(plyr)
library(doParallel)
library(plotly)
detectCores()
registerDoParallel(10)
```

### Loading live imaging data 
```{r}
# total 419 images 
# 10h = 192; 12h = 256; 16h = 384

cor_epiblast <- read_xml(here::here("layers","epiblast","GMEMfinalResult_frame0192.xml")) 
cor_mesoderm <- read_xml(here::here("layers","mesendoderm","GMEMfinalResult_frame0192.xml"))
cor_endoderm <- read_xml(here::here("layers","endoderm","GMEMfinalResult_frame0192.xml"))

links_epiblast <- html_nodes(cor_epiblast, "GaussianMixtureModel")
links_mesoderm <- html_nodes(cor_mesoderm, "GaussianMixtureModel")
links_endoderm <- html_nodes(cor_endoderm, "GaussianMixtureModel")


xml_df_epiblast <- bind_rows(lapply(xml_attrs(links_epiblast), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_mesoderm <- bind_rows(lapply(xml_attrs(links_mesoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_endoderm <- bind_rows(lapply(xml_attrs(links_endoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

colmn <- paste("col", 1:3)

df_epiblast <- cbind(xml_df_epiblast, reshape2::colsplit(xml_df_epiblast$m, " ", colmn))
df_epiblast$type <- "steelblue"
df_epiblast$label <- 0

df_mesoderm <- cbind(xml_df_mesoderm, reshape2::colsplit(xml_df_mesoderm$m, " ", colmn))
df_mesoderm$type <- "orange"
df_mesoderm$label <- 0

df_endoderm <- cbind(xml_df_endoderm, reshape2::colsplit(xml_df_endoderm$m, " ", colmn))
df_endoderm$type <- "red"
df_endoderm$label <- rownames(df_endoderm)

df_1 <- df_epiblast %>% rbind(df_mesoderm) %>%
  rbind(df_endoderm) %>%
  dplyr::select(-type)


df <- df_epiblast %>% rbind(df_mesoderm) %>%
  rbind(df_endoderm) %>%
  dplyr::select(-type)
```


```{r}
cor_epiblast <- read_xml(here::here("layers","epiblast","GMEMfinalResult_frame0193.xml")) 
cor_mesoderm <- read_xml(here::here("layers","mesendoderm","GMEMfinalResult_frame0193.xml"))
cor_endoderm <- read_xml(here::here("layers","endoderm","GMEMfinalResult_frame0193.xml"))

links_epiblast <- html_nodes(cor_epiblast, "GaussianMixtureModel")
links_mesoderm <- html_nodes(cor_mesoderm, "GaussianMixtureModel")
links_endoderm <- html_nodes(cor_endoderm, "GaussianMixtureModel")

xml_df_epiblast <- bind_rows(lapply(xml_attrs(links_epiblast), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_mesoderm <- bind_rows(lapply(xml_attrs(links_mesoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_endoderm <- bind_rows(lapply(xml_attrs(links_endoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

colmn <- paste("col", 1:3)

df_epiblast_2 <- cbind(xml_df_epiblast, reshape2::colsplit(xml_df_epiblast$m, " ", colmn))

df_mesoderm_2 <- cbind(xml_df_mesoderm, reshape2::colsplit(xml_df_mesoderm$m, " ", colmn))

df_endoderm_2 <- cbind(xml_df_endoderm, reshape2::colsplit(xml_df_endoderm$m, " ", colmn))

df_2 <- df_epiblast_2 %>% rbind(df_mesoderm_2) %>%
  rbind(df_endoderm_2)
df_2$label <-0

df <- df %>% 
  rbind(df_2)

```

```{r}
cor_epiblast <- read_xml(here::here("layers","epiblast","GMEMfinalResult_frame0191.xml")) 
cor_mesoderm <- read_xml(here::here("layers","mesendoderm","GMEMfinalResult_frame0191.xml"))
cor_endoderm <- read_xml(here::here("layers","endoderm","GMEMfinalResult_frame0191.xml"))

links_epiblast <- html_nodes(cor_epiblast, "GaussianMixtureModel")
links_mesoderm <- html_nodes(cor_mesoderm, "GaussianMixtureModel")
links_endoderm <- html_nodes(cor_endoderm, "GaussianMixtureModel")

xml_df_epiblast <- bind_rows(lapply(xml_attrs(links_epiblast), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_mesoderm <- bind_rows(lapply(xml_attrs(links_mesoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_endoderm <- bind_rows(lapply(xml_attrs(links_endoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

colmn <- paste("col", 1:3)

df_epiblast_3 <- cbind(xml_df_epiblast, reshape2::colsplit(xml_df_epiblast$m, " ", colmn))

df_mesoderm_3 <- cbind(xml_df_mesoderm, reshape2::colsplit(xml_df_mesoderm$m, " ", colmn))

df_endoderm_3 <- cbind(xml_df_endoderm, reshape2::colsplit(xml_df_endoderm$m, " ", colmn))

df_3 <- df_epiblast_3 %>% rbind(df_mesoderm_3) %>%
  rbind(df_endoderm_3)
df_3$label <-0

df <- df %>% 
  rbind(df_3)

```

```{r}
### Using 4 images to ensure enough spots
cor_epiblast <- read_xml(here::here("layers","epiblast","GMEMfinalResult_frame0194.xml"))
cor_mesoderm <- read_xml(here::here("layers","mesendoderm","GMEMfinalResult_frame0194.xml"))
cor_endoderm <- read_xml(here::here("layers","endoderm","GMEMfinalResult_frame0194.xml"))

links_epiblast <- html_nodes(cor_epiblast, "GaussianMixtureModel")
links_mesoderm <- html_nodes(cor_mesoderm, "GaussianMixtureModel")
links_endoderm <- html_nodes(cor_endoderm, "GaussianMixtureModel")

xml_df_epiblast <- bind_rows(lapply(xml_attrs(links_epiblast), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_mesoderm <- bind_rows(lapply(xml_attrs(links_mesoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

xml_df_endoderm <- bind_rows(lapply(xml_attrs(links_endoderm), function(x) data.frame(as.list(x), stringsAsFactors=FALSE))) %>%
  as.data.frame()

colmn <- paste("col", 1:3)

df_epiblast_4 <- cbind(xml_df_epiblast, reshape2::colsplit(xml_df_epiblast$m, " ", colmn))

df_mesoderm_4 <- cbind(xml_df_mesoderm, reshape2::colsplit(xml_df_mesoderm$m, " ", colmn))

df_endoderm_4 <- cbind(xml_df_endoderm, reshape2::colsplit(xml_df_endoderm$m, " ", colmn))

df_4 <- df_epiblast_4 %>% rbind(df_mesoderm_4) %>%
  rbind(df_endoderm_4)
df_4$label <-0

df <- df %>%
  rbind(df_4)

```

```{r}
# plot(df$`col 2`,df$`col 3`)
# scatterplot3d(df$`col 1`, df$`col 2`, df$`col 3`,pch = 16, color="steelblue")

plot3d(df$`col 1`, df$`col 2`, df$`col 3`,pch = 16, col="steelblue",
       xlab = "", ylab = "", zlab = "", 
       axes = FALSE)

mid_x <- (min(df$`col 1`) + max(df$`col 1`))/2
mid_y <- (min(df$`col 2`) + max(df$`col 2`))/2
mid_z <- (min(df$`col 3`) + max(df$`col 3`))/2

df$new_x <- 2.15*(df$`col 1` - mid_x)
df$new_y <- 2.15*(df$`col 2` - mid_y)
df$new_z <- 2.15*(df$`col 3` - mid_z)

scatterplot3d(df$new_x, df$new_y, df$new_z,pch = 16, color="steelblue")


u <- df[rownames(df) == "3678",] %>%
  rbind(df[rownames(df) == "10836",]) %>%
  rbind(df[rownames(df) == "10408",]) %>%
  select(new_x, new_y, new_z)
  


plot3d(df$new_x,df$new_y,df$new_z,pch = 16, col="steelblue",
       xlab = "", ylab = "", zlab = "", 
       axes = FALSE, size =0.5) + points3d(u$new_x, u$new_y, u$new_z, col = "red", size = 5)
```

### 3 midline spots of ST
```{r}
original_coords <- bulk_coord.df %>%
  dplyr::select(spatial_x_adjusted_3, spatial_y_adjusted_3, spatial_z_adjusted_3)

original_spots <- bulk_coord.df["_DNB_12075_12990",] %>% 
  rbind(bulk_coord.df["_DNB_-8580_10350",]) %>%
  rbind(bulk_coord.df["_DNB_-465_7335",])
```

### Alignment between ST and shell 
```{r}
pm <- original_spots

qm <- u


# kabsch alignment
  pm_dims <- dim(pm)
  if (!all(dim(qm) == pm_dims)) {
    stop(call. = TRUE, "Point sets must have the same dimensions")
  }
  # The rotation matrix will have (ncol - 1) leading ones in the diagonal
  diag_ones <- rep(1, pm_dims[2] - 1)

  # center the points
  pm <- scale(pm, center = TRUE, scale = FALSE)
  qm <- scale(qm, center = TRUE, scale = FALSE)

  am <- crossprod(pm, qm)

  svd_res <- svd(am)
  # use the sign of the determinant to ensure a right-hand coordinate system
  d <- determinant(tcrossprod(svd_res$v, svd_res$u))$sign
  dm <- diag(c(diag_ones, d))

  # rotation matrix
  um <- svd_res$v %*% tcrossprod(dm, svd_res$u)

  # Rotate and then translate to the original centroid location of pm
  rotated_spots <- sweep(t(tcrossprod(um, pm)), 2, -attr(qm, "scaled:center"))


original_coords <- bulk_coord.df %>%
  dplyr::select(spatial_x_adjusted_3, spatial_y_adjusted_3, spatial_z_adjusted_3)
original_coords <- scale(original_coords, center = TRUE, scale = FALSE)
rotated_coords <-  sweep(t(tcrossprod(um, original_coords)), 2, -attr(qm, "scaled:center"))


translation_matrix <- rotated_spots[1,] - rotated_coords["_DNB_12075_12990",] %>%
  as.data.frame() %>% t()

rotated_coords_final <- (rotated_coords + translation_matrix[rep(1,15379),,drop =F]) %>% as.data.frame()

rotated_coords_final["_DNB_12105_13050",]

colnames(rotated_coords_final) <- c("new_x","new_y","new_z")
rotated_coords_final$type <- "orange"

df_new <- df[,c("new_x","new_y","new_z")] 

df_new$type <- "steelblue"

df_final <- df_new %>% rbind(rotated_coords_final)

# v <- u %>% rbind(rotated_coords_final[c("_DNB_12105_13050","_DNB_6945_13920","_DNB_-8955_9375"),] %>% dplyr::select(-type)) 

v <- u %>% rbind(rotated_coords_final[c("_DNB_12075_12990","_DNB_-8580_10350","_DNB_-465_7335"),] %>% dplyr::select(-type)) 

plot3d(df_final$new_x,df_final$new_y,df_final$new_z,pch = 16, col=df_final$type,
       xlab = "", ylab = "", zlab = "", 
       axes = F, size = 1) + points3d(v$new_x, v$new_y, v$new_z, col = "red", size = 10) 

```

### Align the midline to the plane constructed by x-axis and y-axis
```{r}
for (x in seq(330,350,0.05)) {
  for (y in seq(245,260,0.05)) {

# rotate along x-axis
y_mid_1 <- (max(u$new_y) + min(u$new_y))/2
z_mid_1 <- (max(u$new_z) + min(u$new_z))/2
# centre point(0,0,448.5)
a <- x * pi / 180
u$y_2 = cos(a) * (u$new_y-y_mid_1) - sin(a) * (u$new_z - z_mid_1) + y_mid_1

u$z_2 = sin(a) * (u$new_y-y_mid_1) + cos(a) * (u$new_z - z_mid_1) + z_mid_1

u$x_2 <- u$new_x

# rotate along y-axis

b <- y * pi / 180
x_mid_2 <- (max(u$x_2)+min(u$x_2))/2
z_mid_2 <- (max(u$z_2)+min(u$z_2))/2

u$x_3 = cos(b) * (u$z_2-z_mid_2) - sin(b) * (u$x_2 - x_mid_2) + z_mid_2

u$z_3 = sin(b) * (u$z_2-z_mid_2) + cos(b) * (u$x_2 - x_mid_2) + x_mid_2
u$y_3 <- u$y_2


sum_diff <- abs(u$z_3[1] - u$z_3[2]) + abs(u$z_3[2] - u$z_3[3]) + abs(u$z_3[3] - u$z_3[1])

if (sum_diff < 1){
  w <- u
  rotation <- data.frame(x,y)
}
  }
}
# rotation: x = 338.45      y = 252.05
```

```{r}
# rotate along x-axis
y_mid_1 <- (max(df_final$new_y) + min(df_final$new_y))/2
z_mid_1 <- (max(df_final$new_z) + min(df_final$new_z))/2
# centre point(0,0,448.5)
a <- 338.45 * pi / 180
df_final$y_2 = cos(a) * (df_final$new_y-y_mid_1) - sin(a) * (df_final$new_z - z_mid_1) + y_mid_1

df_final$z_2 = sin(a) * (df_final$new_y-y_mid_1) + cos(a) * (df_final$new_z - z_mid_1) + z_mid_1

df_final$x_2 <- df_final$new_x

# rotate along y-axis

b <- 252.05 * pi / 180
x_mid_2 <- (max(df_final$x_2)+min(df_final$x_2))/2
z_mid_2 <- (max(df_final$z_2)+min(df_final$z_2))/2

df_final$x_3 = cos(b) * (df_final$z_2-z_mid_2) - sin(b) * (df_final$x_2 - x_mid_2) + z_mid_2
df_final$z_3 = sin(b) * (df_final$z_2-z_mid_2) + cos(b) * (df_final$x_2 - x_mid_2) + x_mid_2
df_final$y_3 <- df_final$y_2

df_final$z_3 <- df_final$z_3 - mean(df_final[c("3678","10836","10408"),]$z_3)



plot3d(df_final$x_3,df_final$y_3,df_final$z_3,pch = 16, col=df_final$type,
       xlab = "", ylab = "", zlab = "z", 
       axes = T) 

df_final[43899:59277,]$z_3 <- df_final[43899:59277,]$z_3 * 1.1


min(df_final[43899:59277,]$z_3)
max(df_final[43899:59277,]$z_3)

saveRDS(df_final, here::here("output","temp","df_final.rds"))

df_final_filter <- df_final %>% 
  dplyr::filter(between(.$z_3,-372,385))


plot3d(df_final_filter$x_3,df_final_filter$y_3,df_final_filter$z_3,pch = 16, col=df_final_filter$type,
       xlab = "", ylab = "", zlab = "z", 
       axes = T) 

```

### Spot-spot mapping
```{r}
shell_coor <- df_final_filter[1:36487,c("x_3","y_3","z_3")] 
shell_coor_right_1 <- shell_coor %>% 
  dplyr::filter(between(.$z_3,175,385))
shell_coor_right_2 <- shell_coor %>% 
  dplyr::filter(between(.$z_3,0,175))
shell_coor_left_1 <- shell_coor %>% 
  dplyr::filter(between(.$z_3,-372,-170))
shell_coor_left_2 <- shell_coor %>% 
  dplyr::filter(between(.$z_3,-170,0))


st_coor <- df_final_filter[36488:51866,c("x_3","y_3","z_3")] 
st_coor_right_1 <- st_coor %>%
  dplyr::filter(between(.$z_3,175,385))
st_coor_right_2 <- st_coor %>%
  dplyr::filter(between(.$z_3,0,175))
st_coor_left_1 <- st_coor %>%
  dplyr::filter(between(.$z_3,-372,-170))
st_coor_left_2 <- st_coor %>%
  dplyr::filter(between(.$z_3,-170,0))


saveRDS(shell_coor_right_1,here::here("output","mapping","zf10","shell_coor_right_1.rds"))
saveRDS(shell_coor_right_2,here::here("output","mapping","zf10","shell_coor_right_2.rds"))
saveRDS(shell_coor_left_1,here::here("output","mapping","zf10","shell_coor_left_1.rds"))
saveRDS(shell_coor_left_2,here::here("output","mapping","zf10","shell_coor_left_2.rds"))

saveRDS(st_coor_right_1,here::here("output","mapping","zf10","st_coor_right_1.rds"))
saveRDS(st_coor_right_2,here::here("output","mapping","zf10","st_coor_right_2.rds"))
saveRDS(st_coor_left_1,here::here("output","mapping","zf10","st_coor_left_1.rds"))
saveRDS(st_coor_left_2,here::here("output","mapping","zf10","st_coor_left_2.rds"))
```
### Mapping right 1
```{r}
mapping_all <- NULL

shell <- shell_coor_right_1
st <- st_coor_right_1

repeat{
p <- foreach (i = rownames(st)) %dopar% {
  distance_final <- NULL
  distance_final_2 <- NULL
  
  # Calculate the distance from ST spot to shell spots
  spot <- st[i,]
  coordinates <- c(spot$x_3,spot$y_3,spot$z_3)
  
  for(j in rownames(shell)){
  distance <- sqrt(rowSums((shell[j,] - coordinates)^2)) %>% as.data.frame() 
  rownames(distance) <- j
  distance_final <- distance_final %>% rbind(distance)
  }
  distance_final <- distance_final %>% 
    rownames_to_column()
  min_row <- distance_final[which.min(distance_final$.),] %>% as.data.frame()
  
  # Calculate the distance from shell spot to ST spots 
  spot2<- shell[min_row$rowname,]
  coordinates2 <- c(spot2$x_3,spot2$y_3,spot2$z_3)
  
  for(k in rownames(st)){
  distance2 <- sqrt(rowSums((st[k,] - coordinates2)^2)) %>% as.data.frame() 
  rownames(distance2) <- k
  distance_final_2 <- distance_final_2 %>% rbind(distance2)
  }
  distance_final_2 <- distance_final_2 %>% rownames_to_column()
  min_row2 <- distance_final_2[which.min(distance_final_2$.),] %>% as.data.frame()
  
  # Mapping ST spot and shell spot when they are the closet spot to each other
  if(i == min_row2$rowname){
    mapping <- data_frame(min_row$rowname,min_row2$rowname) %>% 
      as.data.frame()
    colnames(mapping) <- c("shell_spots", "st_spots")
    print(mapping)
  } 
} 
mapping_final <- do.call(rbind, p)
mapping_all <- mapping_all %>%
  rbind(mapping_final)
saveRDS(mapping_all,"mapping_right_1.rds")
st <- st[!(rownames(st) %in% mapping_all$st_spots),]
shell <- shell[!(rownames(shell) %in% mapping_all$shell_spots),]

# Exist the repeat when all spots are mapped
if(length(st$x_3) == 0) break;

}
```

### Mapping right 2
```{r}
mapping_all <- NULL

shell <- shell_coor_right_2
st <- st_coor_right_2

repeat{
p <- foreach (i = rownames(st)) %dopar% {
  distance_final <- NULL
  distance_final_2 <- NULL
  
  # Calculate the distance from ST spot to shell spots
  spot <- st[i,]
  coordinates <- c(spot$x_3,spot$y_3,spot$z_3)
  
  for(j in rownames(shell)){
  distance <- sqrt(rowSums((shell[j,] - coordinates)^2)) %>% as.data.frame() 
  rownames(distance) <- j
  distance_final <- distance_final %>% rbind(distance)
  }
  distance_final <- distance_final %>% 
    rownames_to_column()
  min_row <- distance_final[which.min(distance_final$.),] %>% as.data.frame()
  
  # Calculate the distance from shell spot to ST spots 
  spot2<- shell[min_row$rowname,]
  coordinates2 <- c(spot2$x_3,spot2$y_3,spot2$z_3)
  
  for(k in rownames(st)){
  distance2 <- sqrt(rowSums((st[k,] - coordinates2)^2)) %>% as.data.frame() 
  rownames(distance2) <- k
  distance_final_2 <- distance_final_2 %>% rbind(distance2)
  }
  distance_final_2 <- distance_final_2 %>% rownames_to_column()
  min_row2 <- distance_final_2[which.min(distance_final_2$.),] %>% as.data.frame()
  
  # Mapping ST spot and shell spot when they are the closet spot to each other
  if(i == min_row2$rowname){
    mapping <- data_frame(min_row$rowname,min_row2$rowname) %>% 
      as.data.frame()
    colnames(mapping) <- c("shell_spots", "st_spots")
    print(mapping)
  } 
} 
mapping_final <- do.call(rbind, p)
mapping_all <- mapping_all %>%
  rbind(mapping_final)
saveRDS(mapping_all,"mapping_right_2.rds")
st <- st[!(rownames(st) %in% mapping_all$st_spots),]
shell <- shell[!(rownames(shell) %in% mapping_all$shell_spots),]

# Exist the repeat when all spots are mapped
if(length(st$x_3) == 0) break;

}
```

### Mapping left 1
```{r}
mapping_all <- NULL

shell <- shell_coor_left_1
st <- st_coor_left_1

repeat{
p <- foreach (i = rownames(st)) %dopar% {
  distance_final <- NULL
  distance_final_2 <- NULL
  
  # Calculate the distance from ST spot to shell spots
  spot <- st[i,]
  coordinates <- c(spot$x_3,spot$y_3,spot$z_3)
  
  for(j in rownames(shell)){
  distance <- sqrt(rowSums((shell[j,] - coordinates)^2)) %>% as.data.frame() 
  rownames(distance) <- j
  distance_final <- distance_final %>% rbind(distance)
  }
  distance_final <- distance_final %>% 
    rownames_to_column()
  min_row <- distance_final[which.min(distance_final$.),] %>% as.data.frame()
  
  # Calculate the distance from shell spot to ST spots 
  spot2<- shell[min_row$rowname,]
  coordinates2 <- c(spot2$x_3,spot2$y_3,spot2$z_3)
  
  for(k in rownames(st)){
  distance2 <- sqrt(rowSums((st[k,] - coordinates2)^2)) %>% as.data.frame() 
  rownames(distance2) <- k
  distance_final_2 <- distance_final_2 %>% rbind(distance2)
  }
  distance_final_2 <- distance_final_2 %>% rownames_to_column()
  min_row2 <- distance_final_2[which.min(distance_final_2$.),] %>% as.data.frame()
  
  # Mapping ST spot and shell spot when they are the closet spot to each other
  if(i == min_row2$rowname){
    mapping <- data_frame(min_row$rowname,min_row2$rowname) %>% 
      as.data.frame()
    colnames(mapping) <- c("shell_spots", "st_spots")
    print(mapping)
  } 
} 
mapping_final <- do.call(rbind, p)
mapping_all <- mapping_all %>%
  rbind(mapping_final)
saveRDS(mapping_all,"mapping_left_1.rds")
st <- st[!(rownames(st) %in% mapping_all$st_spots),]
shell <- shell[!(rownames(shell) %in% mapping_all$shell_spots),]

# Exist the repeat when all spots are mapped
if(length(st$x_3) == 0) break;

}
```

### Mapping left 2
```{r}
mapping_all <- NULL

shell <- shell_coor_left_2
st <- st_coor_left_2

repeat{
p <- foreach (i = rownames(st)) %dopar% {
  distance_final <- NULL
  distance_final_2 <- NULL
  
  # Calculate the distance from ST spot to shell spots
  spot <- st[i,]
  coordinates <- c(spot$x_3,spot$y_3,spot$z_3)
  
  for(j in rownames(shell)){
  distance <- sqrt(rowSums((shell[j,] - coordinates)^2)) %>% as.data.frame() 
  rownames(distance) <- j
  distance_final <- distance_final %>% rbind(distance)
  }
  distance_final <- distance_final %>% 
    rownames_to_column()
  min_row <- distance_final[which.min(distance_final$.),] %>% as.data.frame()
  
  # Calculate the distance from shell spot to ST spots 
  spot2<- shell[min_row$rowname,]
  coordinates2 <- c(spot2$x_3,spot2$y_3,spot2$z_3)
  
  for(k in rownames(st)){
  distance2 <- sqrt(rowSums((st[k,] - coordinates2)^2)) %>% as.data.frame() 
  rownames(distance2) <- k
  distance_final_2 <- distance_final_2 %>% rbind(distance2)
  }
  distance_final_2 <- distance_final_2 %>% rownames_to_column()
  min_row2 <- distance_final_2[which.min(distance_final_2$.),] %>% as.data.frame()
  
  # Mapping ST spot and shell spot when they are the closet spot to each other
  if(i == min_row2$rowname){
    mapping <- data_frame(min_row$rowname,min_row2$rowname) %>% 
      as.data.frame()
    colnames(mapping) <- c("shell_spots", "st_spots")
    print(mapping)
  } 
} 
mapping_final <- do.call(rbind, p)
mapping_all <- mapping_all %>%
  rbind(mapping_final)
saveRDS(mapping_all,"mapping_left_2.rds")
st <- st[!(rownames(st) %in% mapping_all$st_spots),]
shell <- shell[!(rownames(shell) %in% mapping_all$shell_spots),]

# Exist the repeat when all spots are mapped
if(length(st$x_3) == 0) break;

}
```

```{r}
mapping_right_1 <- readRDS(here::here("output","mapping","zf10","mapping_right_1.rds"))
mapping_right_2 <- readRDS(here::here("output","mapping","zf10","mapping_right_2.rds"))
mapping_left_1 <- readRDS(here::here("output","mapping","zf10","mapping_left_1.rds"))
mapping_left_2 <- readRDS(here::here("output","mapping","zf10","mapping_left_2.rds"))

mapping_all <- mapping_right_1 %>% rbind(mapping_right_2) %>% rbind(mapping_left_1) %>% rbind(mapping_left_2)
```

### Create new seurat object
```{r}
meta <- shell_coor %>% as.data.frame() %>% rownames_to_column() 
colnames(meta)[1] <- "shell_spots"

mapping_meta <- mapping_all %>% 
  left_join(meta)


Merged_seurat_new[["st_spots"]] <- colnames(Merged_seurat_new)

remaining_spots <- df_final %>% 
  dplyr::filter(!between(.$z_3,-372,385)) %>%
  rbind(df_final_filter %>% 
          dplyr::filter(!rownames(.) %in% mapping_all$st_spots) %>%
          dplyr::filter(!rownames(.) %in% mapping_all$shell_spots)) %>% 
  dplyr::filter(rownames(.) %in% rownames(df_1))

remaining_spots_expression <- data.frame(matrix(ncol = length(rownames(remaining_spots)), nrow = length(rownames(Merged_seurat_new))))
rownames(remaining_spots_expression) <- rownames(Merged_seurat_new)
colnames(remaining_spots_expression) <- rownames(remaining_spots)
remaining_spots_expression[is.na(remaining_spots_expression)] <- 0


remaining_spot_seurat <- CreateSeuratObject(remaining_spots_expression)

remaining_spot_seurat@meta.data$x_3 <- remaining_spots$x_3
remaining_spot_seurat@meta.data$y_3 <- remaining_spots$y_3
remaining_spot_seurat@meta.data$z_3 <- remaining_spots$z_3
remaining_spot_seurat@meta.data$bin_annotation <- "blank"
# remaining_spot_seurat@meta.data$colors <- "grey"

subset <- subset(Merged_seurat_new, subset = st_spots %in% mapping_all$st_spots) 
subset@meta.data <- subset@meta.data %>% left_join(mapping_meta)
rownames(subset@meta.data) <- subset@meta.data$st_spots

zf10_final_seurat <- merge(remaining_spot_seurat,subset)



zf10_final_seurat@meta.data$y_3 <- -zf10_final_seurat@meta.data$y_3

coord.df = data.frame(x=zf10_final_seurat@meta.data[colnames(zf10_final_seurat),"x_3",drop = FALSE], y=zf10_final_seurat@meta.data[colnames(zf10_final_seurat),"y_3",drop = FALSE], z=zf10_final_seurat@meta.data[colnames(zf10_final_seurat),"z_3",drop = FALSE], stringsAsFactors=FALSE) 



zf10_final_seurat@images$image =  new(
    Class = 'SlideSeq',
    assay = "Spatial",
    key = "image_",
    coordinates = coord.df
  )

SpatialFeaturePlot(zf10_final_seurat, feature = c("tbxta","gsc","rx3","frzb","cdx4","zic1"), alpha =  c(0.1, 1),pt.size.factor = 3)
```

### Clean up metadata
```{r}
zf10_final_seurat$spatial_x <- NULL
zf10_final_seurat$spatial_y <- NULL
zf10_final_seurat$spatial_x_adjusted <- NULL
zf10_final_seurat$spatial_y_adjusted <- NULL
zf10_final_seurat$spatial_z_adjusted <- NULL
zf10_final_seurat$spatial_x_adjusted_2 <- NULL
zf10_final_seurat$spatial_y_adjusted_2 <- NULL
zf10_final_seurat$spatial_z_adjusted_2 <- NULL
zf10_final_seurat$spatial_x_adjusted_3 <- NULL
zf10_final_seurat$spatial_y_adjusted_3 <- NULL
zf10_final_seurat$spatial_z_adjusted_3 <- NULL
zf10_final_seurat$st_spots <- NULL
zf10_final_seurat$shell_spots <- NULL
zf10_final_seurat$spatial_cluster <- NULL
```

### Save data
```{r}
write_rds(zf10_final_seurat, here::here("output","zf10_final_version.rds"), compress = "gz")
```

### Plot lateral view with annotation
```{r}
expression_df <- zf10_final_seurat@assays$RNA@data %>% as.data.frame()

gene_data <- expression_df["cdx4",,drop = FALSE] %>% 
  t() %>%
  as.data.frame() %>%
  rownames_to_column() %>% 
  left_join(zf10_final_seurat@meta.data %>%
              rownames_to_column())

scene = list(camera = list(eye = list(x = -1.25, y = 1.25, z = 1.25)))

plot_ly(gene_data[6792:22170,],
            type = 'scatter3d',
            x = gene_data[6792:22170,]$x_3,
            y = gene_data[6792:22170,]$y_3,
            z = gene_data[6792:22170,]$z_3,
            
            color = gene_data[6792:22170,]$bin_annotation,
            mode='markers',
            marker = list(
              
              size = 3
       
            ),
            colors = c("#009200","darkgrey","#FEAF16","#683B79","#FFF799","#7f3b08","#F091A0","#6E9BC5","#2ED9FF")
            #opacity = gene_data$alpha
) %>%
   layout(scene = list(
     #camera = list(eye = list(x = 1.5, y = -1.25, z = -1.5)),
     xaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F,showline = F),
     yaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F, showline = F),
     zaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F,showline = F))) %>%
  add_trace(gene_data[1:6791,],
            type = 'scatter3d',
            x = gene_data[1:6791,]$x_3,
            y = gene_data[1:6791,]$y_3,
            z = gene_data[1:6791,]$z_3,
            color = gene_data[1:6791,]$bin_annotation,
            mode='markers',
            marker = list(
              
              size = 1.5
            ),
            alpha = 0.75,

            colors = c("black")
            #opacity = gene_data$alpha
) %>%
   layout(scene = list(
     #camera = list(eye = list(x = 1.5, y = -1.25, z = -1.5)),
     xaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F,showline = F),
     yaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F, showline = F),
     zaxis = list(title = '', showticklabels = F,zeroline = F,showgrid = F,showline = F))) 

plotly::export(p = fig, #the graph to export
               file = "graph 1.png")

```
